---
- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- import_tasks: redhat.yml
  when: ansible_distribution == "RedHat"

# - name: Install python packages
#   pip:
#     name: ["docker", "docker-compose", "dnspython"]
#     state: present
#
# - name: Remove docker-py
#   pip:
#     name: ["docker-py"]
#     state: absent

- name: Ensure Docker is running
  systemd:
    name: docker
    state: started

- meta: flush_handlers
