- name: recogemos la clave docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/gpg

- name: insertamos la clave
  apt_key:
    file: /tmp/gpg
    state: present

- name: Agregamos el repositorio Docker
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list

- name: update apt packages
  apt: update_cache=yes

- name: Eliminamos lxc-docker
  apt: name=lxc-docker state=absent purge=yes

- name: Instalamos Docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - python-pip

- name: Instalamos los paquetes necesarios para docker-compose (para ejecutar docker_service de ansible)
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
    - dnspython

- name: Subimos la configuración del demonio docker
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker

- meta: flush_handlers
