---
- name: Install docker on ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install docker on Centos
  import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Install python packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
    - dnspython

- name: Remove docker-py
  pip:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-py

- name: Create directory /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: Upload docker configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  # when: registry-mirrors == false
  notify:
    - restart docker
