---
- name: UBUNTU -- Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: UBUNTU -- Get key docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/gpg

- name: UBUNTU -- Install apt key
  apt_key:
    file: /tmp/gpg
    state: present

- name: UBUNTU -- Add Docker repository
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: 0644

- name: UBUNTU -- Remove lxc-docker
  apt: name=lxc-docker state=absent purge=yes

- name: UBUNTU -- Install Docker service and pip
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    update_cache: yes
    allow_unauthenticated: yes
  with_items:
    - docker-ce=17.03.0*
    - python-pip
    - net-tools
    - iproute # I need for get ansible_default_ipv4 in other roles like dockerswarm
