---
- name: UBUNTU -- Install apt-transport-https
  apt:
    name: ['apt-transport-https', 'gnupg']
    state: present
    update_cache: true

- name: UBUNTU -- Get key docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/gpg

- name: UBUNTU -- Install apt key
  apt_key:
    file: /tmp/gpg
    state: present

- name: UBUNTU -- Add Docker repository
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: 0644

- name: UBUNTU -- Remove lxc-docker
  apt: name=lxc-docker state=absent purge=yes

- name: UBUNTU -- Install Docker service and pip
  apt:
    name: ["docker-ce={{ docker_version }}", "python-pip", "net-tools", "iproute2", "python-docker", "docker-compose"]
    state: present
    force: true
    update_cache: true
    allow_unauthenticated: true
