---
- name: Converge
  hosts: all
  vars:
    daemon_json:
      registry-mirrors:
        - http://example.com:5001
      insecure-registries:
        - example.com:5000
      dns:
        - 8.8.8.8
        - 9.9.9.9
        - 10.10.10.10
    docker_version: 5:18.09.*
  roles:
    - role: ansible-role-docker
